
// Division 1 - 
var team0 = [ "Coco Browns / Andy",  
   "ST,Patrick Mahones,KAN,QB,0",
   "ST,Ezekiel Elliott,DAL,RB,0",
   "ST,Javonte Williams,DEN,RB,0",
   "ST,Stefon Diggs,BUF,WR,0",
   "ST,A.J. Brown,PHI,WR,0",
   "ST,Hunter Renfro,LVG,WR,0",
   "ST,George Kittle,SFO,TE,0",
   "ST,Justin Tucker,BAL,KR,0",
   "ST,Green Bay Packers,GNB,DEF,0",
   "BN,Ryan Tannehill,TEN,QB,0",
   "BN,Devin Singletary,BUF,RB,0",
   "BN,Kareem Hunt,CLE,RB,0",
   "BN,Jamaal Williams,DET,RB,0",
   "BN,Tyler Lockett,SEA,WR,0",
   "BN,Chase Claypool,PIT,WR,0",
   "BN,Jarvis Landry,NOR,WR,0"
];

var team1 = [ "Phat Bastards / Steve",  
   "ST,Joe Burrow,CIN,QB,0",
   "ST,Saquon Barkley,NYG,RB,0",
   "ST,Rashaad Penny,SEA,RB,0",
   "ST,Tee Higgins,CIN,WR,0",
   "ST,Michael Pittman Jr.,IND,WR,0",
   "ST,Amon-Ra St. Brown,DET,WR,0",
   "ST,Dallas Goedert,PHI,TE,0",
   "ST,Dustin Hopkins,LAC,KR,0",
   "ST,San Franciso 49ers,SFO,DEF,0",
   "BN,Derek Carr,LVG,QB,0",
   "BN,Dameon Pierce,HOU,RB,0",
   "BN,Brian Robinson,WAS,RB,0",
   "BN,Cee Dee Lamb,DAL,WR,0",
   "BN,Brandon Aiyuk,SFO,WR,0",
   "BN,Hayden Hurst,CIN,TE,0",
   "BN,Los Angeles Chargers,LAC,DEF,0"
];

var team2 = [ "Predators / Joe",  
   "ST,Kirk Cousins,MIN,QB,0",
   "ST,Nick Chubb,CLE,RB,0",
   "ST,Travis Etienne Jr.,JAC,RB,0",
   "ST,Justin Jefferson,MIN,WR,0",
   "ST,Deebo Samuel,SFO,WR,0",
   "ST,Mike Evans,TAM,WR,0",
   "ST,T.J. Hockenson,DET,TE,0",
   "ST,Greg Joseph,MIN,KR,0",
   "ST,Los Angeles Rams,LAR,DEF,0",
   "BN,Trey Lance,SFO,QB,0",
   "BN,Breece Hall,NYJ,RB,0",
   "BN,Rhamondre Stevenson,NWE,RB,0",
   "BN,Kenneth Walker III,SEA,RB,0",
   "BN,Rachaad White,TAM,RB,0",
   "BN,Rashod Bateman,BAL,WR,0",
   "BN,Elijah Moore,NYJ,WR,0"
];

var team3 = [ "Roll Tide / Daniel",  
   "ST,Lamar Jackson,BAL,QB,0",
   "ST,Austin Ekeler,LAC,RB,0",
   "ST,Cam Akers,LAR,RB,0",
   "ST,Tyreek Hill,MIA,WR,0",
   "ST,Keeban Allen,LAC,WR,0",
   "ST,Chris Godwin,TAM,WR,0",
   "ST,Mark Andrews,BAL,TE,0",
   "ST,Harrison Butker,KAN,KR,0",
   "ST,Tampa Bay Buccaneers,TAM,DEF,0",
   "BN,Russell Wilson,DEN,QB,0",
   "BN,Eli Mitchell,SFO,RB,0",
   "BN,Clyde Edwards-Helaire,KAN,RB,0",
   "BN,James Robinson,JAC,RB,0",
   "BN,Garrett Wilson,NYJ,RB,0",
   "BN,Christian Watson,GNB,WR,0",
   "BN,DJ Chark,DET,WR,0"
];

var team4 = [ "Seamen / Adam",  
   "ST,Kyler Murray,ARI,QB,0",
   "ST,Christian McCaferey,CAR,RB,0",
   "ST,Alvin Kamara,NOR,RB,0",
   "ST,D'Andre Swift,DET,RB,0",
   "ST,Allen Robinson II,LAR,WR,0",
   "ST,Gabriel Davis,BUF,WR,0",
   "ST,Cole Kmet,CHI,TE,0",
   "ST,Denver Broncos,DEN,DEF,0",
   "BN,AJ Dillon,GNB,RB,0",
   "BN,Kenneth Gainwell,PHI,RB,0",
   "BN,Darnell Mooney,CHI,RB,0",
   "BN,Allen Lazard,GNB,WR,0",
   "BN,Christian Kirk,JAC,WR,0",
   "BN,Kadarius Toney,NYG,WR,0",
   "BN,Chris Olave,NOR,WR,0",
   "BN,Jameson Williams,DET,WR,0"
];

// Divison 2 - 
var team5 = [ "Iceotopes / John F",  
   "ST,Dak Prescott,DAL,QB,0",
   "ST,Joe Mixon,CIN,RB,0",
   "ST,James Conner,ARI,RB,0",
   "ST,Leonard Fournette,TAM,RB,0",
   "ST,DJ Moore,CAR,WR,0",   
   "ST,Mike Williams,LAC,WR,0",
   "ST,Kyle Pitts,ATL,TE,0",
   "ST,Tyler Bass,BUF,KR,0",
   "ST,Buffalo Bills,BUF,DEF,0",
   "BN,J.D. McKissic,WAS,RB,0",
   "BN,Nyheim Hines,IND,RB,0",
   "BN,Robert Woods,TEN,RB,0",
   "BN,DeAndre Hopkins,ARI,WR,0",
   "BN,Tyler Boyd,CIN,WR,0",
   "BN,Marques Valdes-Scantling,KAN,WR,0",
   "BN,Jahan Dotson,WAS,WR,0"
];

var team6 = [ "Najee Bt Nature / Matt",  
   "ST,Josh Allen,BUF,QB,0",
   "ST,Najee Narris,PIT,RB,0",
   "ST,Chase Edmonds,MIA,RB,0",
   "ST,Courtland Sutton,DEN,WR,0",
   "ST,Marquise Brown,ARI,WR,0",
   "ST,Jaylen Waddle,MIA,WR,0",
   "ST,Travis Kelce,KAN,TE,0",
   "ST,Daniel Carlson,LVG,KR,0",
   "ST,New England Patriots,NWE,DEF,0",
   "BN,Josh Jacobs,LVG,RB,0",
   "BN,Michael Carter,NYJ,RB,0",
   "BN,Melvin Gordon III,DEN,RB,0",
   "BN,Khalil Herbert,CHI,RB,0",
   "BN,DeVonta Smith,PHI,WR,0",
   "BN,Robert Woods,TEN,WR,0",
   "BN,Dawson Knox,BUF,TE,0"
];

var team7 = [ "Discount Belicheck / Harrison",
   "ST,Justin Herbert,LAC,QB,0",
   "ST,Derrick Henry,TEN,RB,0",
   "ST,David Montgomery,CHI,RB,0",
   "ST,Ja'Marr Chase,CIN,WR,0",
   "ST,DK Metcalf,SEA,WR,0",
   "ST,Amari Cooper,CLE,WR,0",
   "ST,Zach Ertz,ARI,TE,0",
   "ST,Evan McPherson,CIN,KR,0",
   "ST,New Orleans Saints,NOR,DEF,0",
   "BN,Tua Tagovailoa,MIA,QB,0",
   "BN,J.K. Dobbins,BAL,RB,0",
   "BN,Antonio Gibson,WAS,RB,0",
   "BN,Raheem Mostert,MIA,RB,0",
   "BN,Drake London,ATL,WR,0",
   "BN,Jakobi Meyers,NWE,RB,0",
   "BN,Russel Gage,TAM,WR,0"
];

var team8 = [ "Porkchops / Noah G",  
   "ST,Aaron Rodgers,GNB,QB,0",
   "ST,Jonathan Taylor,IND,RB,0",
   "ST,Dalvin Cook,MIN,RB,0",
   "ST,JuJu Smitch-Schuster,KAN,WR,0",
   "ST,Jerry Jeudy,DEN,WR,0",
   "ST,Terry McLaurin,WAS,WR,0",
   "ST,Dalton Schultz,DAL,TE,0",
   "ST,Brandon McManus,DEN,KR,0",
   "ST,Baltimore Ravens,BAL,DEF,0",
   "BN,Matthew Stafford,LAR,QB,0",
   "BN,Tony Pollard,DAL,RB,0",
   "BN,Cordarrelle Patterson,ATL,RB,0",
   "BN,Adam Thielen,MIN,WR,0",
   "BN,Julio Jones,TAM,WR,0",
   "BN,Skyy Moore,KAN,WR,0",
   "BN,Isaiah McKenzie,BUF,WR,0"
];

var team9 = [ "Tenacious Anus / Jake",  
   "ST,Tom Brady,TAM,QB,0",
   "ST,Aaron Jones,GNB,RB,0",
   "ST,Miles Sanders,PHI,RB,0",
   "ST,Cooper Kupp,LAC,WR,0",
   "ST,Davante Adams,LVG,WR,0",
   "ST,Diontae Johnson,PIT,WR,0",
   "ST,Darren Waller,LVG,TE,0",
   "ST,Matt Gay,LAR,KR,0",
   "ST,Pitsburgh Steelers,PIT,DEF,0",
   "BN,Damien Harris,NWE,QB,0",
   "BN,Darrel Henderson Jr.,LAR,RB,0",
   "BN,Alexander Mattison,MIN,RB,0",
   "BN,James Cook,BUF,RB,0",
   "BN,Isiah Spiller,LAC,RB,0",
   "BN,Brandin Cooks,HOU,WR,0",
   "BN,Michael Thomas,NOR,RB,0"
];



