
// Division 1 - 
var team0 = [ "Predators / Joe",
   "ST,Lamar Jackson,BAL,QB,0",
   "ST,Johnathan Taylor,IND,RB,0",
   "ST,Joe Mixon,CIN,RB,0",
   "ST,Calvin Ridley,ATL,WR,0",
   "ST,Terry McLaurin,WAS,WR,0",
   "ST,Robert Woods,LAR,WR,0",
   "ST,Mike Gesicki,PHI,TE,0",
   "ST,Greg Zuerlein,DAL,KR,0",
   "ST,Cleveland Browns,CLE,DEF,0",
   "BN,Trey Lance,SFO,QB,0",
   "BN,D'Andre Swift,DET,RB,0",
   "BN,Javonte Williams,DEN,RB,0",
   "BN,Noah Fant,DEN,TE,0",
   "BN,Jerry Jeudy,DEN,WR,0",
   "BN,Antonio Brown,TAM,WR,0",
   "BN,Mecole Hardman,KAN,WR,0"
];

var team1 = [ "Discount Belicheck / Harrison",
   "ST,Dak Prescott,DAL,QB,0",
   "ST,Ezekiel Elliott,DAL,RB,0",
   "ST,Saquon Barkley,NYG,RB,0",
   "ST,Deandre Hopkins,ARI,WR,0",
   "ST,CeeDee Lamb,DAL,WR,0",
   "ST,Brandon Alyuk,SFO,WR,0",
   "ST,Austin Hooper,CLE,TE,0",
   "ST,Harrison Butker,KAN,KR,0",
   "ST,Baltimore Ravens,BAL,DEF,0",
   "BN,Tua Tagovailoa,MIA,QB,0",
   "BN,Mac Jones,NYG,QB,0",
   "BN,Gus Edwards,BAL,RB,0",
   "BN,David Johnson,HOU,RB,0",
   "BN,Devin Singletary,BUF,RB,0",
   "BN,Jarvis Landry,CLE,WR,0",
   "BN,Jonnu Smith,NWE,TE,0"
];

var team2 = [ "Tenacious Anus / Jake",
   "ST,Russell Wilson,SEA,QB,0",
   "ST,Austin Ekeler,LAC,RB,0",
   "ST,Myles Gaskin,MIA,RB,0",
   "ST,Tyreek Hill,KAN,WR,0",
   "ST,DK Metcalf,SEA,WR,0",
   "ST,Brandon Cooks,HOU,WR,0",
   "ST,Mark Andrews,BAL,TE,0",
   "ST,Tyler Bass,BUF,KR,0",
   "ST,Los Angeles Rams,LAR,DEF,0",
   "BN,Kirk Cousins,MIN,QB,0",
   "BN,Josh Jacobs,LVG,RB,0",
   "BN,Kenyan Drake,LVG,RB,0",
   "BN,Leonard Fournette,TAM,RB,0",
   "BN,JuJu SMith-Schuster,PIT,WR,0",
   "BN,Ja'Marr Chase,CIN,WR,0",
   "BN,Tyler Higbee,LAR,RB,0"
];

var team3 = [ "Coco Browns / Andy",
   "ST,Patrick Mahones,KAN,QB,0",
   "ST,David Montgomery,CHI,RB,0",
   "ST,James Robinson,JAC,RB,0",
   "ST,Justin Jefferson,MIN,WR,0",
   "ST,Julio Jones,TEN,WR,0",
   "ST,Robby Anderson,CAR,WR,0",
   "ST,Darren Waller,LVG,TE,0",
   "ST,Justin Tucker,BAL,KR,0",
   "ST,San Francisco 49ers,SFO,DEF,0",
   "BN,Ryan Tannehill,TEN,QB,0",
   "BN,Darrell Henderson,LAR,RB,0",
   "BN,A.J. Dillon,GNB,RB,0",
   "BN,Malcolm Brown,MIA,RB,0",
   "BN,Curtis Samuel,WAS,WR,0",
   "BN,Elijah Moore,NYJ,WR,0",
   "BN,Rob Gronkowski,TAM,TE,0"
];

var team4 = [ "Seamen / Adam",
   "ST,Jalen Hurts,PHI,QB,0",
   "ST,Christian McCaferey,CAR,RB,0",
   "ST,Antonio Gibson,WAS,RB,0",
   "ST,Keenan Allen,LAC,WR,0",
   "ST,Diontae Johnson,PIT,WR,0",
   "ST,Tyler Lockett,SEA,WR,0",
   "ST,T.J. Hockenson,DET,TE,0",
   "ST,Matt Prater,ARI,KR,0",
   "ST,New England Patriots,NWE,DEF,0",
   "BN,Trevor Lawrence,JAC,QB,0",
   "BN,Raheem Mostert,SFO,RB,0",
   "BN,Jamaal Williams,DET,RB,0",
   "BN,Allen Robinson II,CHI,WR,0",
   "BN,Corey Davis,WAS,WR,0",
   "BN,Laviska Shenault,JAC,WR,0",
   "BN,Jakobi Meyers,NWE,WR,0"
];

// Divison 2 - 

var team5 = [ "Iceotopes / John F",
   "ST,Kyler Murray,ARI,QB,0",
   "ST,Aaron Jones,GNB,RB,0",
   "ST,Kareem Hunt,CLE,RB,0",
   "ST,Adam Thielan,CLE,RB,0",   
   "ST,Stefon Diggs,BUF,WR,0",
   "ST,Cooper Kupp,LAR,WR,0",
   "ST,Robert Tonyan,GNB,TE,0",
   "ST,Ryan Succop,TAM,KR,0",
   "ST,Tampa Bay Buccaneers,TAM,DEF,0",
   "BN,Matthew Stafford,LAR,QB,0",
   "BN,Melvin Gordon III,DEN,RB,0",
   "BN,Zack Moss,BUF,RB,0",
   "BN,Tony Pollard,DAL,RB,0",
   "BN,Tyler Boyd,CIN,WR,0",
   "BN,Parris Campbell,IND,WR,0",
   "BN,Sterling Shepard,NYG,WR,0"
];

var team6 = [ "Phat Bastards / Steve",
   "ST,Matt Ryan,ATL,QB,0",
   "ST,Dalvin Cook,MIN,RB,0",
   "ST,Najee Harris,PIT,RB,0",
   "ST,Courtland Sutton,DEN,WR,0",
   "ST,Michael Pittman Jr.,IND,WR,0",
   "ST,D.J. Moore,CAR,WR,0",
   "ST,George Kittle,SFO,TE,0",
   "ST,Jason Myers,SEA,KR,0",
   "ST,Washington FB Team,WAS,DEF,0",
   "BN,Baker Mayfield,CLE,QB,0",
   "BN,Trey Sermon,SFO,RB,0",
   "BN,Philip Lindsay,SFO,RB,0",
   "BN,D.J. Chark Jr.,JAC,WR,0",
   "BN,Marquise Brown,BAL,WR,0",
   "BN,Anthony Firsker,TEN,TE,0",
   "BN,Michael Thomas,NOR,WR,0"
];

var team7 = [ "Porkchops / Noah G",
   "ST,Aaron Rodgers,GNB,QB,0",
   "ST,Alvin Kamara,NOR,RB,0",
   "ST,Chris Carson,SEA,RB,0",
   "ST,Mike Evans,TAM,WR,0",
   "ST,Amari Cooper,DAL,WR,0",
   "ST,Deebo Samuel,SFO,WR,0",
   "ST,Travis Kelce,KAN,TE,0",
   "ST,Matt Gay,LAR,KR,0",
   "ST,Buffalo Bills,BUF,DEF,0",
   "BN,Tom Brady,TAM,QB,0",
   "BN,Damien Harris,NWE,RB,0",
   "BN,Michael Carter,NYJ,RB,0",
   "BN,Odell Beckham Jr.,CLE,WR,0",
   "BN,Jaylin Waddle,MIA,WR,0",
   "BN,Marquez Callaway,NOR,WR,0",
   "BN,Rhamondre Stevenson,NWE,RB,0"
];

var team8 = [ "Roll Tide / Daniel",
   "ST,Justin Herbert,LAC,QB,0",
   "ST,Nick Chubb,CLE,RB,0",
   "ST,Clyde Edward-Helaire,KAN,RB,0",
   "ST,Davante Adams,GNB,WR,0",
   "ST,Chris Godwin,TAM,WR,0",
   "ST,Kenny Golladay,NYG,WR,0",
   "ST,Kyle Pitts,ATL,TE,0",
   "ST,Chase McLaughlin,CLE,KR,0",
   "ST,Denver Broncos,DEN,DEF,0",
   "BN,Justin Fields,CHI,QB,0",
   "BN,Miles Sanders,PHI,RB,0",
   "BN,Sony Michel,LAR,RB,0",
   "BN,James Conner,ARI,RB,0",
   "BN,Nyheim Hines,IND,RB,0",
   "BN,Devonta Smith,PHI,WR,0",
   "BN,Michael Gallup,DAL,WR,0"
];

var team9 = [ "Fuller go eazy on the Pepsi / Matt",
   "ST,Josh Allen,BUF,QB,0",
   "ST,Derrick Henry,TEN,RB,0",
   "ST,Chase Edmonds,ARI,RB,0",
   "ST,A.J. Brown,TEN,WR,0",
   "ST,Mike Williams,LAC,WR,0",
   "ST,Tee Higgins,CIN,WR,0",
   "ST,Logan Thomas,WAS,TE,0",
   "ST,Younghoe Koo,ATL,KR,0",
   "ST,Pittsburgh Steelers,PIT,DEF,0",
   "BN,Joe Burrow,CIN,QB,0",
   "BN,Mike Davis,ATL,RB,0",
   "BN,Ronald Jones II,TAM,RB,0",
   "BN,Latavius Murray,NOR,RB,0",
   "BN,Will Fuller,MIA,WR,0",
   "BN,Chase Claypool,PIT,WR,0",
   "BN,Dallas Goedert,PHI,TE,0"
];


