
// Division 1 - 
var team0 = [ "Predators / Joe",
   "ST,Ben Roethlisberger,PIT,QB,0",
   "ST,Chris Carson,SEA,RB,0",
   "ST,James Conner,PIT,RB,0",
   "ST,Davante Adams,GNB,WR,0",
   "ST,Keenan Allen,LAC,WR,0",
   "ST,Amari Cooper,DAL,WR,0",
   "ST,Zach Ertz,PHI,TE,0",
   "ST,Matt Prater,DET,KR,0",
   "ST,Indianapolis Colts,IND,DEF,0",
   "BN,Matthew Stafford,DET,QB,0",
   "BN,Cam Akers,LAR,RB,0",
   "BN,Kareem Hunt,CLE,RB,0",
   "BN,Zack Moss,BUF,RB,0",
   "BN,Marvin Jones Jr,DET,WR,0",
   "BN,Darius Slayton,NYG,WR,0"
];

var team1 = [ "Discount Belicheck / Harrison",
   "ST,Lamar Jackson,BAL,QB,0",
   "ST,Derrick Henry,TEN,RB,0",
   "ST,David Johnson,HOU,RB,0",
   "ST,JuJu Smith-Schuster,PIT,WR,0",
   "ST,A.J. Brown,TEN,WR,0",
   "ST,Jarvis Landry,CLE,WR,0",
   "ST,Mark Andrews,BAL,TE,0",
   "ST,Will Lutz,NOR,KR,0",
   "ST,Pittsburgh Steelers,PIT,DEF,0",
   "BN,Joe Burrow,CIN,QB,0",
   "BN,Melvin Gordon III,ARI,RB,0",
   "BN,Ronald Jones II,TAM,RB,0",
   "BN,John Brown,BUF,WR,0",
   "BN,Hayden Hurst,ARI,TE,0",
   "BN,Alexander Mattison,MIN,RB,0"
];

var team2 = [ "Tenacious Anus / Jake",
   "ST,Josh Allen,BUF,QB,0",
   "ST,Saquon Barkley,NYG,RB,0",
   "ST,Le'Veon Bell,NYJ,RB,0",
   "ST,Julio Jones,ARI,WR,0",
   "ST,Stefon Diggs,BUF,WR,0",
   "ST,Julian Edelman,NWE,WR,0",
   "ST,Travis Kelce,KAN,TE,0",
   "ST,Younghue Koo,ATL,KR,0",
   "ST,Los Angeles Rams,LAR,DEF,0",
   "BN,A.J. Green,CIN,WR,0",
   "BN,Antonio Gibson,WAS,RB,0",
   "BN,DeVante Parker,MIA,WR,0",
   "BN,Tyler Boyd,CIN,WR,0",
   "BN,D'Andre Swift,DET,RB,0",
   "BN,Matt Breida,MIA,RB,0"
];

var team3 = [ "Coco Browns / Andy",
   "ST,Patrick Mahones,KAN,QB,0",
   "ST,Dalvin Cook,MIN,RB,0",
   "ST,Miles Sanders,PHI,RB,0",
   "ST,Odell Beckham Jr,CLE,WR,0",
   "ST,Courtland Sutton,DEN,WR,0",
   "ST,David Montgomery,CHI,RB,0",
   "ST,Darren Waller,LVG,TE,0",
   "ST,Justin Tucker,BAL,KR,0",
   "ST,San Francisco 49ers,SFO,DEF,0",
   "BN,Tom Brady,NWE,QB,0",
   "BN,Will Fuller V,HOU,WR,0",
   "BN,T.J. Hockenson,DET,TE,0",
   "BN,Latavious Murray,NOR,RB,0",
   "BN,Golden Tate,NYG,WR,0",
   "BN,Mike Gesicki,MIA,TE,0"
];

var team4 = [ "Seaman / Adam",
   "ST,Kyler Murray,ARI,QB,0",
   "ST,Ezekiel Elliott,DAL,RB,0",
   "ST,Aaron Jones,GNB,RB,0",
   "ST,Kenny Golladay,DET,WR,0",
   "ST,Allen Robinson II,MIN,WR,0",
   "ST,DJ Moore,CAR,WR,0",
   "ST,Evan Engram,NYG,TE,0",
   "ST,Dan Bailey,MIN,KR,0",
   "ST,Minnesota Vikings,MIN,DEF,0",
   "BN,Terry McLaurin,WAS,WR,0",
   "BN,James White,NWE,RB,0",
   "BN,Sterling Shepard,NYG,WR,0",
   "BN,Jordan Howard,MIA,RB,0",
   "BN,Christian Kirk,ARI,WR,0",
   "BN,Michael Gallup,DAL,WR,0"
];

// Divison 2 - 

var team5 = [ "Iceotopes / John F",
   "ST,Carson Wentz,PHI,QB,0",
   "ST,Joe Mixon,DAL,RB,0",
   "ST,Raheem Mostert,SFO,RB,0",
   "ST,Cooper Kupp,LAR,WR,0",
   "ST,Dede Westbrook,JAC,WR,0",
   "ST,Nick Chubb,CLE,RB,0",   
   "ST,George Kittle,SFO,TE,0",
   "ST,Harrison Butker,KAN,KR,0",
   "ST,New Orleans Saints,NOR,DEF,0",
   "BN,Matt Ryan,ATL,QB,0",
   "BN,Marlon Mack,IND,RB,0",
   "BN,Deebo Samuel,SFO,WR,0",
   "BN,Mark Ingram II,BAL,RB,0",
   "BN,Sony Michel,NWE,RB,0",
   "BN,Darrell Henderson,LAR,RB,0"
];

var team6 = [ "Phat Bastards / Steve",
   "ST,Matt Ryan,ATL,QB,0",
   "ST,Dalvin Cook,MIN,RB,0",
   "ST,Najee Harris,PIT,RB,0",
   "ST,Courtland Sutton,DEN,WR,0",
   "ST,Michael Pittman Jr.,IND,WR,0",
   "ST,D.J. Moore,CAR,WR,0",
   "ST,George Kittle,SFO,TE,0",
   "ST,Jason Myers,SEA,KR,0",
   "ST,Washington FB Team,WAS,DEF,0",
   "BN,Baker Mayfield,CLE,QB,0",
   "BN,Trey Sermon,SFO,RB,0",
   "BN,Philip Lindsay,SFO,RB,0",
   "BN,D.J. Chark Jr.,JAC,WR,0",
   "BN,Marquise Brown,BAL,WR,0",
   "BN,Anthony Firsker,TEN,TE,0",
   "BN,Michael Thomas,NOR,WR,0"
];

var team7 = [ "Porkchops / Noah G",
   "ST,Drew Brees,NOR,QB,0",
   "ST,Christian McCaffrey,CAR,RB,0",
   "ST,Alvin Kamara,NOR,RB,0",
   "ST,DeAndre Hopkins,ARI,WR,0",
   "ST,Tyler Lockett,SEA,WR,0",
   "ST,T.Y. Hilton,IND,WR,0",
   "ST,Rob Gronkowski,MIN,TE,0",
   "ST,Chris Boswell,PIT,KR,0",
   "ST,Seattle Seahawks,SEA,DEF,0",
   "BN,Johnathan Taylor,IND,RB,0",
   "BN,Marquise Brown,BAL,WR,0",
   "BN,Brandin Cooks,HOU,WR,0",
   "BN,Cam Newton,NWE,QB,0",
   "BN,Baker Mayfield,CLE,QB,0",
   "BN,Tevin Coleman,SFO,RB,0"
];

var team8 = [ "Roll Tide / Daniel",
   "ST,Russell Wilson,SEA,QB,0",
   "ST,Austin Ekeler,LAC,RB,0",
   "ST,Tarik Cohen,CHI,RB,0",
   "ST,Tyreek Hill,KAN,WR,0",
   "ST,Chris Godwin,TAM,WR,0",
   "ST,Adam Thielen,MIN,WR,0",
   "ST,Jared Cook,NOR,TE,0",
   "ST,Robbie Gould,SFO,KR,0",
   "ST,Denver Broncos,DEN,DEF,0",
   "BN,Jimmy Garoppolo,SFO,QB,0",
   "BN,Devin Singletary,BUF,RB,0",
   "BN,DK Metcalf,SEA,WR,0",
   "BN,J.K. Dobbins,BAL,RB,0",
   "BN,CeeDee Lamb,DAL,WR,0",
   "BN,Duke Johnson,HOU,RB,0"
];

var team9 = [ "Fuller go eazy on the Pepsi / Matt",
   "ST,Dak Prescott,DAL,QB,0",
   "ST,Clyde Edwards-Helaire,KAN,RB,0",
   "ST,Todd Gurley,ATL,RB,0",
   "ST,Michael Thomas,NOR,WR,0",
   "ST,DJ Chark,JAC,WR,0",
   "ST,Mike Evans,LAC,WR,0",
   "ST,Hunter Henry,LAC,TE,0",
   "ST,Greg Zuerleib,DAL,KR,0",
   "ST,New England Patriots,NWE,DEF,0",
   "BN,Philip Lindsay,NWE,RB,0",
   "BN,Emmanuel Sanders,IND,WR,0",
   "BN,Leonard Fournette,TAM,RB,0",
   "BN,Noah Fant,DEN,TE,0",
   "BN,Gardner Minshew II,KAN,QB,0",
   "BN,Henry Ruggs III,LVG,WR,0"
];


